#ifndef CONFIG_H_
#define CONFIG_H_

#define CONFIG_KEEPALIVE_ENABLE 0
#define CONFIG_KEEPALIVE_TIMEOUT_SEC 60
#define CONFIG_INPUT_BUFF_LEN 1024
#define CONFIG_OUTPUT_BUFF_LEN 1024
#define CONFIG_MAX_PATH_SIZE 128

#endif